### ISSUE TITLE
Notion playwright 說明中的 `yarn test` 是否應該為 `yarn playwright test` ？  (否)

### ISSUE THREAD

**Issue by AndrewTeraSuns** [ntuee-web-programming/112-1-hack1-QnAs#1]
請問 Notion Hack1-preREADME 的
[這裡](https://www.notion.so/Hack1-preREADME-e7b7186f755d46cc953c302d300e0a97?pvs=4#5c8fb81611d047f691fe355024e3f457)
的 `yarn test` 是否應該為 `yarn playwright test` ？

![image](https://github.com/ntuee-web-programming/112-1-hack1-QnAs/assets/63439849/1b76a9ea-6b11-44de-b626-30d5f03edcf5)

**Comment by guan404ming** [comment]
yarn test 是正確的～
