### ISSUE TITLE
TODO 1.4 

### ISSUE THREAD

**Issue by ppg0921** [ntuee-web-programming/112-1-hack1-QnAs#11]
請問TODO 1.4 中，"It should be controlled by the `username` state."，是什麼意思? 是他顯示的東西要被影響還是其他東西要被影響?

**Comment by joshmtlau** [comment]
意思是說 `username` 這個 state 要反映該 input field 的變動。
這邊的 controlled 指的是 input field 的 rendering 被 `username` 所決定。

**Comment by vivicheng031** [comment]
請問助教剛剛說可以用帳號密碼是甚麼

**Comment by guanboo-yang** [comment]
名稱：test
密碼：123

**Comment by ruby0322** [comment]
@vivicheng031 
https://cool.ntu.edu.tw/courses/32374/discussion_topics/238474#
