### ISSUE TITLE
TODO 1.1 評分code

### ISSUE THREAD

**Issue by MimiChen1123** [ntuee-web-programming/112-1-hack1-QnAs#12]
我目前上傳gradescope想要確認我自己分數，但是會發現1.1會有問題，我看到問題是因為測的時候他要求src要是某個值，可是對於Layout.tsx應該不會是對的路徑才對？

**Comment by madmaxieee** [comment]
請問你的學號？

**Comment by MimiChen1123** [comment]
助教抱歉，應該是我自己的問題，所以應該沒事了。抱歉。

**Comment by MartyJan** [comment]
助教您好, 想請問 TODO1.1 是在 tab 上顯示 title 嗎？我目前 tab 上有顯示 title, 但 gradescope 沒有分數
