### ISSUE TITLE
TODO 1.5

### ISSUE THREAD

**Issue by kylechu0731** [ntuee-web-programming/112-1-hack1-QnAs#13]
想請問TODO1.5檢查registering時password有沒有match具體是match什麼呢

**Comment by joshmtlau** [comment]
> 想請問TODO1.5檢查registering時password有沒有match具體是match什麼呢

是指兩次密碼輸入要相同這件事

**Comment by BrianLii** [comment]
助教您好
我已經設定
required={(location.pathname === "/register")}
但是
await expect(confirmPasswordInput).toHaveAttribute('required', '')
還是過不了欸
不知道是哪邊出了問題
