### ISSUE TITLE
TODO 1.4

### ISSUE THREAD

**Issue by BrianLii** [ntuee-web-programming/112-1-hack1-QnAs#16]
助教您好
我用 login('test', '123'); 的時候都會
AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}

後端有出現
 Server is running on port 8000.

**Comment by joshmtlau** [comment]
你有在前端的 `.env` 設定好 VITE_API_URL 嗎？

**Comment by BrianLii** [comment]
有了 抱歉忽略了QQ
