### ISSUE TITLE
TODO 3.1

### ISSUE THREAD

**Issue by enip2473** [ntuee-web-programming/112-1-hack1-QnAs#17]
<img width="434" alt="image" src="https://github.com/ntuee-web-programming/112-1-hack1-QnAs/assets/84924924/070e5649-2d88-4709-9c05-5ab3fca7d2eb">

但我除了 onChange 什麼都沒改

正常要死也是下面那幾行死(?

**Comment by ruby0322** [comment]
同學您好，
由於 Manaco Editor 啟動時間不穩定，這個錯誤訊息很可能是啟動過慢，導致 script 定位不到。
雖然不確定錯誤訊息的確切根源，但你可以先忽略，繼續做這題。重丟幾次，應該就會過，在 gradescope 上已經有其他同學通過該測試。
如果還有問題歡迎再發問，謝謝！

**Comment by ric2k1** [comment]
解決了嗎？

**Comment by enip2473** [comment]
持續不穩定 一下過一下沒有
