### ISSUE TITLE
gradescope score

### ISSUE THREAD

**Issue by lorettayao** [ntuee-web-programming/112-1-hack1-QnAs#29]
can i see my gradescope score? how can i make sure i submit the correct fie?
我直接用電腦壓縮，交出一個zip file? can i do it like that? because my zip file generated by commands is 0 byte

**Comment by ruby0322** [comment]
是的，將你壓縮的 zip 檔繳交至 gradescope 上，待平台測試完成，會即時顯示分數。
但是 zip 檔 0 byte 應該有誤，請檢查是否遵照 readme 繳交流程。

**Comment by joshmtlau** [comment]
Hi, you may find #30 useful
