### ISSUE TITLE
請問gitignore的部份要怎麼處理？

### ISSUE THREAD

**Issue by Paul2k3** [ntuee-web-programming/112-1-hack1-QnAs#3]
請問.env之類的會需要我們自己設定嗎？ 然後.env檔案之類的是不是也不能夠推上去？

**Comment by ntuee-webprogramming** [comment]
.env 請依照.env.example 的指示填寫
.env 檔案與作業相同，不能推上github，照理說把code直接放進wp1121內後會自動ignore

**Comment by Paul2k3** [comment]
那如果是在gradescope的部份呢？

**Comment by guan404ming** [comment]
> .env 請依照.env.default的指示填寫 .env 檔案與作業相同，不能推上github，照理說把code直接放進wp1121內後會自動ignore

*.env.example

**Comment by joshmtlau** [comment]
> 那如果是在gradescope的部份呢？

Gradescope 測試部分，我們會 supply 測試用的 .env，不會使用到同學的 .env 喔～

**Comment by Paul2k3** [comment]
所以連modules 跟 .env都丟到gradescope
上去也沒有關係嗎？

**Comment by madmaxieee** [comment]
是不建議啦，如果你有正確 setup 而且按照指示的指令生 zip 檔是不會包含那些東西的。
