### ISSUE TITLE
打開App出現Error

### ISSUE THREAD

**Issue by LienZiLi** [ntuee-web-programming/112-1-hack1-QnAs#32]
![image](https://github.com/ntuee-web-programming/112-1-hack1-QnAs/assets/117928480/83ffa34c-a21b-46c1-915f-44bb6f4d54d9)
請問打開App出現這個要怎麼辦QQ

**Comment by ric2k1** [comment]
建議 console.log 看看是哪裡丟出這個 error 的

**Comment by ruby0322** [comment]
同學您好，是否能在你最近一次修改的地方加上 console.log 印出你懷疑可能造成錯誤的內容？或者直接螢幕截圖。

**Comment by ric2k1** [comment]
或是註解掉一些 code, 看看 error 會不會消失

**Comment by LienZiLi** [comment]
找到問題了，謝謝QQ
