### ISSUE TITLE
TODO 3.1 waiting for getByTestId('tab-create')

### ISSUE THREAD

**Issue by hsieh22** [ntuee-web-programming/112-1-hack1-QnAs#33]
助教您好，我在執行3.1時遇到以下問題
然而整份code裡面我找不到testid是tab-create的element，想請問如何解決？

TimeoutError: locator.click: Timeout 1500ms exceeded.
=========================== logs ===========================
waiting for getByTestId('tab-create')
============================================================

   9 |   const editor = page.getByTestId('editor').locator('.monaco-editor').nth(0)
  10 |
> 11 |   await page.getByTestId('tab-create').click()
     |                                        ^
  12 |   await filenameInput.fill('Lorem Post 3')
  13 |   await editor.click()
  14 |   await page.keyboard.type(`console.log("Hello, Lorem Post 3!")`)

    at /Users/hsiehyuanlung/Desktop/Web Programming/wp1121/hack1/tests/public-3.spec.ts:11:40

**Comment by ruby0322** [comment]
同學您好，

這個元件長這樣：

<TabsTrigger
                asChild
                key={tab.title}
                value={`/${tab.path}`}
                className="px-8"
                data-testid={`tab-${tab.path}`}
              >
                <NavLink
                  to={`/${tab.path}`}
                  className="flex flex-row items-center justify-center gap-1.5"
                >
                  <tab.icon size={14} className="-ml-0.5" />
                  <span className="text-sm">{tab.title}</span>
                </NavLink>
              </TabsTrigger>

位在：frontend/src/routes/Layout.tsx
