### ISSUE TITLE
expect....error

### ISSUE THREAD

**Issue by boyuancao** [ntuee-web-programming/112-1-hack1-QnAs#38]
不好意思助教我沒有很懂前面的意思，所以來這邊直接發文抱歉
我的錯誤訊息是這個
expect.toHaveText— utils.ts:34
想請問一下是什麼意思
也有很多expect...的相關錯誤
因為我有很多個都有類似的expect錯誤，但是其他都對
而且功能在我自己打開來運行都很正常

謝謝助教

**Comment by joshmtlau** [comment]
expect... 的語法是測試程式的語法。大致上的概念是，假設你 implement 了 a + b，測試程式可能就會像 expect (3 + 5 === 8);
如果錯誤是偶發的，有可能是 test scripts 啟動時間偏長所以 timeout
如果固定都有錯，代表你一定有地方不符合 spec 的要求，可以看一下跳什麼樣的錯誤來協助自己找出問題

**Comment by madmaxieee** [comment]
expect.toHaveText 是指那個element裡面要包什麼字
