### ISSUE TITLE
關於 git archive -o hack1.zip HEAD:hack1

### ISSUE THREAD

**Issue by yenting-biao** [ntuee-web-programming/112-1-hack1-QnAs#9]
請問按照 README 執行 submit 的指令時，輸入 `git archive -o hack1.zip HEAD:hack1` 會提示
`fatal: 尚未追蹤目前的工作目錄`
是正常的嗎？

**Comment by madmaxieee** [comment]
還是要記得執行 add 跟 commit 喔

**Comment by ric2k1** [comment]
有按照指示 rename folder 以及放到 wp1121 底下嗎？

**Comment by yenting-biao** [comment]
有的，也有執行 add 跟 commit

**Comment by yenting-biao** [comment]
不好意思我發現問題了，應該要在 wp1121 folder 底下執行而不是在 hack1 folder

**Comment by ric2k1** [comment]
你有把 hack1 底下的 .git 移除掉嗎？

**Comment by ruby0322** [comment]
同學您好，請確保在 wp1121 工作目錄下 `rm -rf ./hack1/.git` 指令，以避免繳交時的錯誤。

**Comment by yenting-biao** [comment]
有的，如上一則留言，我剛剛不小心在錯的工作目錄執行`git archive`指令，不好意思問題已解決，感謝助教及老師

**Comment by andrew891103** [comment]
那我可以同問這個指令他說not a valid object name: HEAD:hack1 要怎麼排除嗎 謝謝助教

**Comment by joshmtlau** [comment]
方才有詢問無法順利繳交的同學，請參考 #30 
若仍有問題，請改至 #30 下方回應，謝謝！
